#!/bin/bash
# Simple deployment script for vlgdbzo3

echo "============================================================"
echo "Remote Exec Server - Quick Deploy to vlgdbzo3"
echo "============================================================"
echo ""
echo "Pre-configured API Key: REMOTE_EXEC_KEY_REVOKED_PLACEHOLDER_0000000000000000"
echo ""
echo "Step 1: Copy file to vlgdbzo3"
echo "------------------------------------------------------------"
echo "Run this command:"
echo ""
echo "gcloud compute scp remote_exec_server.py zo3adm@vlgdbzo3:/home/zo3adm/ \\"
echo "  --zone=europe-west3-a \\"
echo "  --project=sap-development"
echo ""
echo "Step 2: Install dependencies on vlgdbzo3"
echo "------------------------------------------------------------"
echo "SSH to vlgdbzo3 and run:"
echo ""
echo "python3 -m pip install --user fastapi uvicorn"
echo ""
echo "Step 3: Start the server on vlgdbzo3"
echo "------------------------------------------------------------"
echo "python3 /home/zo3adm/remote_exec_server.py"
echo ""
echo "The server will start on port 9999 with the pre-configured API key."
echo "No need to copy/paste any keys - everything is already configured!"
echo ""
echo "Step 4: Test from HANA Sentinel"
echo "------------------------------------------------------------"
echo "python test_http_executor.py"
echo ""
echo "============================================================"
